version:  "3.9"
services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: ledbetter_test
      MYSQL_ROOT_PASSWORD: topsecret
